atelier_ideal/atelier_ideal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from filebrowser.sites import site

urlpatterns = [
    path('', include('website.urls', namespace='website')),
    path('admin/filebrowser/', site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('admin/password_reset/', auth_views.PasswordResetView.as_view(), name='admin_password_reset',),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done',),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm',),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete',),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atelier_ideal/website/urls.py
from django.urls import path
from . import views
from .views import ArticleDetailView, EventDetailView

urlpatterns = [
    path('', views.index, name='index'),
    path('events/', views.events, name='events'),
	path('article/<slug:slug>/', ArticleDetailView.as_view(), name='article-detail'),
    path('event/<int:pk>', EventDetailView.as_view(), name='event-detail'),
]

app_name = 'website'

atelier_ideal/website/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from solo.models import SingletonModel
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from filebrowser.fields import FileBrowseField
from filebrowser.base import FileObject


STATUS = (
    (0, 'Brouillon'),
    (1, 'Publié')
)

class Article(models.Model):
    title = models.CharField(verbose_name="Titre", max_length=200, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    author = models.ForeignKey(User, verbose_name="Auteur", on_delete=models.CASCADE, related_name='article')
    updated_on = models.DateTimeField(verbose_name="Dernière modification", auto_now=True)
    content = RichTextUploadingField(verbose_name="Contenu", blank=True, null=True)
    created_on = models.DateTimeField(verbose_name="Date de création", auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    photo = FileBrowseField(verbose_name="Photo", max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class EventType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Type d'événements"
        verbose_name_plural = "Types d'événements"


class Event(models.Model):
    title = models.CharField(verbose_name="Titre de l'événement", max_length=50)
    subtitle = models.CharField(verbose_name="Sous-titre de l'événement", max_length=50, blank=True)
    infos = models.CharField(verbose_name="Prix / restauration", max_length=50, blank=True, null=True)
    event_type = models.ForeignKey(EventType, verbose_name="Type d'événement", on_delete=models.PROTECT)
    event_date = models.DateTimeField(verbose_name="Date de l'événement",)
    description = RichTextUploadingField(verbose_name="Description de l'événement", blank=True, null=True)
    photo = FileBrowseField(verbose_name="Photo de l'événement", max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'un événement'
        verbose_name_plural = 'Événements'
        ordering = ['-event_date']


class Ad(SingletonModel):
    title = models.CharField(verbose_name="Titre", max_length=50, blank=True, null=True)
    content = RichTextUploadingField(verbose_name="Contenu", blank=True, null=True)

    def __str__(self):
        return self.title or ''

    class Meta:
        verbose_name = 'Annonce'


class Settings(SingletonModel):
    name = models.CharField(verbose_name="Nom", max_length=50, blank=True, null=True)
    slogan = models.CharField(verbose_name="Slogan", max_length=200, blank=True, null=True)
    address = models.CharField(verbose_name="Adresse", max_length=200, blank=True, null=True)
    email = models.EmailField(verbose_name="Email", max_length=200, blank=True, null=True)
    phone = models.CharField(verbose_name="Téléphone", max_length=20, blank=True, null=True)
    facebook = models.URLField(verbose_name="Facebook", max_length=200, blank=True, null=True)
    twitter = models.URLField(verbose_name="Twitter", max_length=200, blank=True, null=True)
    logo = FileBrowseField(verbose_name="Logo", max_length=200, null=True, blank=True)
    banner = FileBrowseField(verbose_name="Bannière", max_length=200, null=True, blank=True)
    favicon = FileBrowseField(verbose_name="Favicon", max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = 'Configuration'

atelier_ideal/website/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse
from django.utils import timezone
from django.views import generic
from django.urls import reverse_lazy
from .models import Event, EventType, Ad, Article, Settings
from datetime import datetime, timedelta
from django.utils.safestring import mark_safe

from django.views.generic.detail import DetailView

def index(request):
    template = loader.get_template('website/index.html')
    context = {
        'articles': Article.objects.filter(status=1),
        'events': Event.objects.all().filter(event_date__gte = timezone.now()).order_by('event_date')[:10],
    }

    return render(request, 'website/index.html', context)


def events(request):
    date = request.GET.get('date')
    eventType = request.GET.get('type')
    keyword = request.GET.get('keyword')

    events = Event.objects.all().order_by('event_date')

    if date != '' and date is not None:
        events = events.filter(event_date__gte=date)
    else:
        events = events.filter(event_date__gte=timezone.now())
    if eventType != 'Tous' and eventType is not None:
        events = events.filter(event_type__name=eventType)
    if keyword != '' and keyword is not None:
        events = events.filter(title__icontains=keyword) | events.filter(subtitle=keyword) | events.filter(description__icontains=keyword)
    context = {
        'date': date or datetime.now().strftime("%Y-%m-%d"),
        'chosenType': eventType,
        'eventTypes': EventType.objects.all(),
        'keyword': keyword or '',
        'events': events
    }

    return render(request, 'website/events.html', context)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'website/article_detail.html'


class EventDetailView(DetailView):
    model = Event
    template_name = 'website/event_detail.html'

atelier_ideal/website/templates/website/_footer.html
{% load static sass_tags solo_tags %}
{% get_solo 'website.Settings' as settings %}

<footer class="footer">
  <div class="content has-text-centered">
    <div class="columns">
      <div class="column">
        <p class="has-text-centered">
          <span class="footer-logo">
            <img src="{{ settings.logo.url }}" alt="logo" width="100%" height="100%">
          </span>
          {{ settings.slogan }} <br>
          <i class="fas fa-map-marker-alt"></i>
          {{ settings.address }}<br>
          <i class="fas fa-mobile-alt"></i>
          {{ settings.phone }}<br>
          <i class="far fa-envelope"></i>
          {{ settings.email }}<br>
          <br>
          {% if settings.facebook %}
            <span>
              <a href="{{ settings.facebook }}">
                <i class="fab fa-facebook-square fa-lg"></i>
              </a>
            </span>
          {% endif %}
          {% if settings.twitter %}
            <span>
              <a href="{{ settings.twitter }}">
                <i class="fab fa-twitter-square fa-lg"></i>
              </a>
            </span>
          {% endif %}
        </p>
      </div>
      <div class="column">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2888.654122065069!2d1.4346557157463484!3d43.61374276299893!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12aebb5c709bf75f%3A0x692e865a9f0eeb7c!2s36%20Rue%20Danielle%20Casanova%2C%2031000%20Toulouse!5e0!3m2!1sfr!2sfr!4v1588237646469!5m2!1sfr!2sfr" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
      </div>
    </div>
  </div>
</footer>

<link href="{% sass_src 'website/scss/components/footer.scss' %}" rel="stylesheet" type="text/css" />

atelier_ideal/website/templates/website/_navbar.html
{% load static sass_tags solo_tags flatpages %}
{% get_solo 'website.Settings' as settings %}

<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item logo" href="{% url 'website:index' %}">
      <img src="{{ settings.logo.url }}" width="100%" height="100%" alt="logo">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div>
        <span class="title">{{ settings.name }}</span><br>
        <span class="subtitle">{{ settings.slogan }}</span>
      </div>
    </div>
    <div class="navbar-end">
      <a class="navbar-item" href="{% url 'website:index' %}">
        Accueil
      </a>

      <a class="navbar-item" href="{% url 'website:events' %}">
        Les événements
      </a>

      {% get_flatpages '/projets/' as projects_pages %}
      {% if projects_pages %}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Un Projet ?
          </a>

          <div class="navbar-dropdown">
            {% for page in projects_pages %}
              <a class="navbar-item" href="{{ page.url }}">
                {{ page.title }}
              </a>
            {% endfor %}
          </div>
        </div>
      {% endif %}

      {% get_flatpages '/collectifs/' as collective_pages %}
      {% if collective_pages %}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Les Collectifs
          </a>

          <div class="navbar-dropdown">
            {% for page in collective_pages %}
              <a class="navbar-item" href="{{ page.url }}">
                {{ page.title }}
              </a>
            {% endfor %}
          </div>
        </div>
      {% endif %}

      {% get_flatpages '/lieu/' as places_pages %}
        {% if places_pages %}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Le lieu
          </a>

          <div class="navbar-dropdown">
            {% for page in places_pages %}
              <a class="navbar-item" href="{{ page.url }}">
                {{ page.title }}
              </a>
            {% endfor %}
          </div>
        </div>
      {% endif %}

      {% get_flatpages '/ailleurs/' as elsewhere_pages %}
      {% if elsewhere_pages %}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Ailleurs
          </a>

          <div class="navbar-dropdown">
            {% for page in elsewhere_pages %}
              <a class="navbar-item" href="{{ page.url }}">
                {{ page.title }}
              </a>
            {% endfor %}
          </div>
        </div>
      {% endif %}

   </div>
  </div>
</nav>

  <link href="{% sass_src 'website/scss/components/navbar.scss' %}" rel="stylesheet" type="text/css" />

  <script type="text/javascript" src="{% static 'website/js/navbar.js' %}"></script>

atelier_ideal/website/templates/website/article_detail.html
{% extends 'website/base.html' %}

{% load static sass_tags %}

{% block content %}
	<div class="detail">
		<h1 class="title is-size-2">
			{{ article.title | safe }}
		</h1>
		<span class="date-container is-size-6">
			Publié le {{ article.created_on | date:"d F Y" | lower }}
			{% if article.updated_on > article.created_on %}
				 | Mis à jour le {{ article.updated_on | date:"d F Y" | lower }}
			{% endif %}
		</span>
		<hr>
		<article>
			<div class="content">
				{{ article.content | safe }}
			</div>
		</article>
	</div>

	<link rel="stylesheet" type="text/css" href="{% sass_src 'website/scss/components/detail.scss' %}">

{% endblock %}

atelier_ideal/website/templates/website/base.html
{% load static solo_tags sass_tags %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>La chapelle</title>
    {% get_solo 'website.Settings' as settings %}
    <link rel="icon" href="{{ settings.favicon.url }}" />
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/js/all.min.js"></script>
    <link href="{% sass_src 'website/scss/main.scss' %}" rel="stylesheet" type="text/css" />

  </head>
  <body>

  <!-- Nav bar -->
  {% include 'website/_navbar.html' %}

  {% block content %}
  {% endblock %}

  </body>

  {% include 'website/_footer.html' %}

</html>

atelier_ideal/website/templates/website/event_detail.html
{% extends 'website/base.html' %}

{% load static sass_tags %}

{% block content %}
	<section class="detail">
		<div class="event-header">
			<div class="event-infos">
				<h1 class="title is-4">{{ event.title }}</h1>
				<h2 class="subtitle is-6">{{ event.subtitle }}</h2>
				<div class="event-detail">
					<span>
						<span class="icon">
							<i class="fas fa-tag"></i>
						</span>
						{{ event.event_type }}
					</span>
					<span>
						<span class="icon">
							<i class="far fa-calendar-alt"></i>
						</span>
						<time datetime="{{ event.event_date }}">{{ event.event_date | date:"D d M Y"}}</time>
						<span class="icon">
							<i class="far fa-clock"></i>
						</span>
						<time datetime="{{ event.event_date }}">{{ event.event_date | date:"G:i"}}</time>
					</span>
					{% if event.infos %}
						<span>
							<span class="icon">
								<i class="fas fa-info-circle"></i>
							</span>
							{{ event.infos }}
						</span>
					{% endif %}
				</div>
			</div>
			<div class="event-picture">
			  {% if event.photo %}
			    <figure class="image">
			      <img src="{{ event.photo.url }}" alt="event image">
			    </figure>
			  {% endif %}
			</div>
		</div>
		<hr>
		<article>
			<div class="content">
				{{ event.description | safe }}
			</div>
		</article>
	</section>

	<link rel="stylesheet" type="text/css" href="{% sass_src 'website/scss/components/detail.scss' %}">

{% endblock %}

atelier_ideal/website/templates/website/events.html
{% extends 'website/base.html' %}
{% load static sass_tags %}

{% block content %}
  <section class="events">
    <div class="container">
        <div class="form-container ">
          <form method="get">

            <div class="field">
              <div class="field-label">
                <label class="label">&#192; partir du</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    <input name="date" class="input" id="datetime" type="date" value="{{ date }}">
                  </div>
                </div>
              </div>
            </div>

            <div class="field">
              <div class="field-label">
                <label class="label">Type d'évènement</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    {% if eventTypes %}
                      <div class="select">
                        <select class="input" name="type">
                          <option value="Tous">Tous</option>
                          {% for eventType in eventTypes %}
                            {% if chosenType == eventType.name %}
                              <option value="{{ eventType.name }}" selected="selected">{{ eventType.name }}</option>
                            {% else %}
                              <option value="{{ eventType.name }}">{{ eventType.name }}</option>
                            {% endif %}
                          {% endfor %}
                        </select>
                      </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>

            <div class="field">
              <div class="field-label">
                <label class="label">Recherche</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    <input type="text" class="input" name="keyword" value="{{ keyword }}" placeholder="Mot clé">
                  </div>
                </div>
              </div>
            </div>

            <div class="control has-text-centered">
              <button type="submit" class="button is-large">Chercher</button>
            </div>
          </form>
        </div>

        <div class="events-container">
          {% if events %}
            {% for event in events %}

              <div class="event card">
                <div class="card-content">
                  <div class="media">
                    <div class="media-left">
                      {% if event.photo %}
                        <figure class="image">
                          <img src="{{ event.photo.url }}" alt="event image">
                        </figure>
                      {% endif %}
                    </div>
                    <div class="media-content">
                      <h1 class="title title-link is-4"><a href="{% url 'website:event-detail' event.pk %}">{{ event.title }}</a></h1>
                      <h2 class="subtitle is-6">{{ event.subtitle }}</h2>
                      <div class="event-detail">
                        <div>
                          <span class="icon">
                            <i class="fas fa-tag"></i>
                          </span>
                          {{ event.event_type }}
                        </div>
                        <div>
                          <span class="icon">
                            <i class="far fa-calendar-alt"></i>
                          </span>
                          <time datetime="{{ event.event_date }}">{{ event.event_date | date:"D d M Y"}}</time>
                          <span class="icon">
                            <i class="far fa-clock"></i>
                          </span>
                          <time datetime="{{ event.event_date }}">{{ event.event_date | date:"G:i"}}</time>
                        </div>
                        {% if event.infos %}
                          <div>
                            <span class="icon">
                              <i class="fas fa-info-circle"></i>
                            </span>
                            {{ event.infos }}
                          </div>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>

                <hr>

                <div class="content has-text-centered has-text-justified">
                  <article>
                    <div class="content">
                      {{ event.description | safe | truncatewords_html:100 }}
                    </div>
                  </article>
                  <br>
                  <span class="link-container">
                    <a href="{% url 'website:event-detail' event.pk %}">Voir les détails >></a>
                  </span>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <span class="text-container has-text-centered">Aucun évènement ne correspond à votre recherche</span>
          {% endif %}
        </div>
    </div>
  </section>


<link rel="stylesheet" type="text/css" href="{% sass_src 'website/scss/components/events.scss' %}">

{% endblock %}

atelier_ideal/website/templates/website/index.html
{% extends 'website/base.html' %}

{% load sass_tags solo_tags static utils %}

{% block content %}
	{% get_solo 'website.Settings' as settings %}
	<section class="hero-container">
		<div class="hero-image" style="background-image: url({{ settings.banner.url }})">
		</div>
	</section>

	<div class="columns">
		<div class="column is-9">

			{% get_solo 'website.Ad' as ad %}
			{% if ad.content and ad.title %}
				<section class="ads">
					<div class="card">
						<div class="card-content">
							<h1 class="title is-size-5">
						      {{ ad.title | safe }}
						    </h1>
							<div class="content">{{ ad.content | safe }}</div>
						</div>
					</div>
				</section>
			{% endif %}


			{%if articles%}
				<section class="articles">
					<h1 class="title section-title is-size-5">Dernières publications</h1>
					<div class="articles-container">
						{% for article in articles %}
							<div class="article box">
								{% if article.photo %}
									<figure>
										<p class="image">
											<img src="{{ article.photo.url }}" alt="article image">
										</p>
									</figure>
								{% endif %}
								<h1 class="title has-text-centered title-link is-size-5">
							      <a href="{% url 'website:article-detail' article.slug %}">{{ article.title | safe }}</a>
							    </h1>
								<div class="content has-text-justified">{{ article.content | safe | truncatewords_html:50 }}</div>
								<span class="date-container is-size-6">
									<i class="fas fa-feather-alt"></i> {{ article.created_on | date:"d F Y" | lower }}
								</span>
							</div>
						{% endfor %}
					</div>
				</section>
			{% endif %}
		</div>
		<div class="column events-index-container is-3">
			<div class="events-index">
				{% if events %}
					<h1 class="title section-title is-size-5">&#192; venir ...</h1>
					{% for event in events %}
						<div class="box">
							<article class="media">
								<div class="media-left">
									<figure class="image is-64x64">
										<div class="event-day-letter">
											<div class="day-letter is-size-7">
												{{ event.event_date | date:"l" | upper }}
											</div>
											<div class="day-letter is-size-3">
												{{ event.event_date | date:"d"}}
											</div>
										</div>
									</figure>
								</div>
								<div class="media-content">
									<div class="content event-title">
										<h3 class="title is-size-5 title-link"><a href="{% url 'website:event-detail' event.pk %}">{{ event.title }}</a></h3>
										<h4 class="subtitle is-size-6">{{ event.subtitle }}</h4>
									</div>
									<div class="content event-infos">
										<div class="infos-date">
											<span class="icon">
												<i class="far fa-clock"></i>
											</span>
											<time datetime="{{ event.event_date }}">{{ event.event_date | date:"G:i" }}</time>
										</div>
										{% if event.infos %}
											<div class="infos-price">
												<span class="icon">
													<i class="fas fa-info-circle"></i>
												</span>
												{{ event.infos }}
											</div>
										{% endif %}
									</div>
								</div>
							</article>
						</div>
					{% endfor %}
					<hr>
					<div class="event-footer has-text-centered">
						<span>
							<a href="{% url 'website:events' %}">Voir tout les événements</a>
						</span>
						<span>
							{% load flatpages %}
							{% get_flatpages '/projets/' as projects_pages %}
							{% if projects_pages %}
								{% for page in projects_pages %}
									{% if 'demande' in page.title %}
										<a href="{{ page.url }}">Proposer un événement</a>
									{% endif %}
								{% endfor %}
							{% endif %}
						</span>
					</div>
				{% endif %}
			</div>
		</div>
	</div>

	<link href="{% sass_src 'website/scss/components/index.scss' %}" rel="stylesheet" type="text/css" />

{% endblock %}